version: "3"
services:
  main_server:
    container_name: container_mc_notificacoes_app
    build: ./App
    environment:
      - DB_HOST=db_noti_server
      - DB_PORT=3306
      - DB_DB=RAS_MC_Notificacoes
      - DB_USER=mc_notificacoes_4B
      - DB_PASS=mc_notificacoes_4B
    ports:
      - "7004:5000"
    depends_on:
      - db_noti_server
    networks:
      - my_network

  db_noti_server:
    container_name: container_mc_notificacoes_db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=RAS_MC_Notificacoes
      - MYSQL_USER=mc_notificacoes_4B
      - MYSQL_PASSWORD=mc_notificacoes_4B
      - MYSQL_ROOT_PASSWORD=mc_notificacoes_4B
    restart: always
    ports:
      - "3309:3306"    
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge