version: "3"
services:
  main_server:
    container_name: container_mc_users_app
    build: ./App
    environment:
      - DB_HOST=db_server_users
      - DB_PORT=3306
      - DB_DB=RAS_MC_Users
      - DB_USER=mc_users_4B
      - DB_PASS=mc_users_4B
    ports:
      - "7002:5001"
    depends_on:
      - db_server_users
    networks:
      - my_network

  db_server_users:
    container_name: container_mc_users_db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=RAS_MC_Users
      - MYSQL_USER=mc_users_4B
      - MYSQL_PASSWORD=mc_users_4B
      - MYSQL_ROOT_PASSWORD=mc_users_4B
    restart: always
    ports:
      - "3311:3306"    
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge