version: "3"
services:
  main_server:
    container_name: container_mc_correcao_app
    build: ./App
    environment:
      - DB_HOST=db_server
      - DB_PORT=3306
      - DB_DB=RAS_MC_Correcao
      - DB_USER=mc_correcao_4B
      - DB_PASS=mc_correcao_4B
    ports:
      - "7000:5000"
    depends_on:
      - db_server
    networks:
      - my_network

  db_server:
    container_name: container_mc_correcao_db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=RAS_MC_Correcao
      - MYSQL_USER=mc_correcao_4B
      - MYSQL_PASSWORD=mc_correcao_4B
      - MYSQL_ROOT_PASSWORD=mc_correcao_4B
    restart: always
    ports:
      - "3308:3306"    
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge